### PR TITLE
Make android an optional dependency

### PR DESCRIPTION
**Pull request by quidryan**
This should react to the presence of the Android plugin, but not require it as a dependency.

### CODE REVIEW

**Comment by quidryan** [comment]
Java 1.6 is EOL. Java 1.7 is deprecated and will be EOL'd soon. This plugin really should move on to 1.7.

**Comment by hierynomus** [comment]
Hi Justin,

Thx for the PR! 
I agree, let's upgrade to 1.7. 

Does travis not rebuild for the new commit?

**Comment by hierynomus** [comment]
Ahh also upgrade the travis.yml file, that one specifies openjdk6 still ;)

**Comment by quidryan** [comment]
Pushing now with a .travisci.yml fix.

**Comment by hierynomus** [comment]
Thanks again Justin!

**Pull request merged**
