### PR TITLE
Ignore fatal errors in POMs of transitive dependencies

### PR DESCRIPTION
**Pull request by sschuberth**

### CODE REVIEW

**Comment by hierynomus** [comment]
Thanks Sebastian,

Would it be an idea to make this configurable behaviour? I could imagine you want to be informed and "actively choose" to ignore those broken dependencies.

It might be an even better idea to explicitly be able to list those dependencies in the build.gradle file and link them either to the right license, or to the 'noLicense'.

**Comment by sschuberth** [comment]
Hmm, I see several issues here. If the POM cannot be parsed as it's malformed, you actually don't know the license. Which is different from 'noLicense' because you cannot even tell that no license has been specified.

Prior to my commits, the behavior was that the task would throw an exception not write a results file. I don't think that's a feasible behavior, even if some one deliberately has not enabled to ignore malformed POMs. Of course I could introduce a property like `ignore.malformed.poms` which can be set to `true` or `false`, but how should the plugin behave in the case of `false`?

**Comment by hierynomus** [comment]
I think that an error from the build is exactly what you want. Suppose it is an internal artifact (not a public one) that has a malformed POM. Then instead of ignoring this you want to fix it.

Also even if the POM is malformed, you might actually know yourself which license it is, so then an explicit mapping of the artifact would be preferred instead of just assigning the empty license to it.

**Comment by sschuberth** [comment]
Note that my fix only applies to malformed transitive dependencies. And these are not so likely to be internals ones, probably. For first-order dependencies already Gradle itself would choke on malformed POMs during dependency resolution. But anyway, I see your point, also I tend to disagree :-)

I'll see what I can do.

**Comment by sschuberth** [comment]
@hierynomus I'll split the unrelated commits to other PRs so you can merge them right away.

**Comment by sschuberth** [comment]
@hierynomus I've updated the PR, please have a look (and merge PR #107 first to get the tests working again).

**Comment by hierynomus** [comment]
Thanks!

**Comment by sschuberth** [comment]
@hierynomus Thanks for merging! Can I expect a new release with this included?

**Comment by hierynomus** [comment]
And it is there: 0.13.0 (https://plugins.gradle.org/plugin/com.github.hierynomus.license)

**Comment by sschuberth** [comment]
Great, thanks! Unfortunately, I've discovered an issue due to the upgrade to the Android Gradle plugin. It breaks using your plugin in a project which depends on an older version of the Android Gradle plugin. I already have a fix and a PR is underway.

**Comment by sschuberth** [comment]
@hierynomus See https://github.com/hierynomus/license-gradle-plugin/pull/109.

**Pull request merged**
